on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'           # Push events to every tag not containing /
name: Create Release Binaries
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@main
      - name: Build stuff
        run: |
          yarn install
          yarn build
          yarn build:binaries
          cd out
          zip kyve-linux.zip kyve-linux
          rm kyve-linux
          zip kyve-macos.zip kyve-macos
          rm kyve-macos
          cd ..
      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.vars.outputs.tag_name }}
          files: out/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

